kind: Service
apiVersion: v1
metadata:
  name: validated-core-resource
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    # Remove the quotes to fix the validation issue.
    port: "8080"
    targetPort: 8080
