kind: KubeconformValidator
apiVersion: kubeconformvalidator.aabouzaid.com/v1alpha1
metadata:
  name: validate
  annotations:
    config.kubernetes.io/function: |
      # Exec KRM functions.
      exec:
       path: ../dist/kubeconformvalidator

      # # Containerized KRM functions.
      # container:
      #   image: aabouzaid/kubeconformvalidator
      #   network: true
spec:
  # Kubeconform args:
  # https://github.com/yannh/kubeconform#Usage
  args:
  - -output
  - json
  - -skip
  - 'AlertmanagerConfig'
